# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jg < Formula
  desc "A frecency-based CLI for quickly jumping to Git repositories"
  homepage "https://github.com/silee-tools/jg"
  version "0.1.10"
  license "MIT"

  depends_on "fzf"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/silee-tools/jg/releases/download/v0.1.10/jg-v0.1.10-darwin-amd64.tar.gz"
      sha256 "2eb8440508c91d09dfb12a37714872c004724d1b0c1eb46b2bf987e240329e5e"

      define_method(:install) do
        bin.install "jg"
        zsh_completion.install "completions/_jg"
        bash_completion.install "completions/jg.bash" => "jg"
        (share/"jg"/"plugin").install "plugin/jg.plugin.zsh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/silee-tools/jg/releases/download/v0.1.10/jg-v0.1.10-darwin-arm64.tar.gz"
      sha256 "2a3ad011b2f0bbc1733e73878882cd917c766e3bbe8e10b78d7c33e969386093"

      define_method(:install) do
        bin.install "jg"
        zsh_completion.install "completions/_jg"
        bash_completion.install "completions/jg.bash" => "jg"
        (share/"jg"/"plugin").install "plugin/jg.plugin.zsh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/silee-tools/jg/releases/download/v0.1.10/jg-v0.1.10-linux-amd64.tar.gz"
      sha256 "a425fca7eeb3d7bc512054f9f2aec79bb7f3f6f4a7ad239a41c0aebfb6be32fc"
      define_method(:install) do
        bin.install "jg"
        zsh_completion.install "completions/_jg"
        bash_completion.install "completions/jg.bash" => "jg"
        (share/"jg"/"plugin").install "plugin/jg.plugin.zsh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/silee-tools/jg/releases/download/v0.1.10/jg-v0.1.10-linux-arm64.tar.gz"
      sha256 "808b753cf0d5b44245512970927cd7034547d3cb495f77985521f15d6f8aac87"
      define_method(:install) do
        bin.install "jg"
        zsh_completion.install "completions/_jg"
        bash_completion.install "completions/jg.bash" => "jg"
        (share/"jg"/"plugin").install "plugin/jg.plugin.zsh"
      end
    end
  end

  def caveats
    <<~EOS
      Run 'jg setup' to configure shell integration,
      then restart your shell or run: exec $SHELL
    EOS
  end

  test do
    assert_match "jg", shell_output("#{bin}/jg --help 2>&1")
  end
end
