# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jg < Formula
  desc "A frecency-based CLI for quickly jumping to Git repositories"
  homepage "https://github.com/silee-tools/jg"
  version "0.1.6"
  license "MIT"

  depends_on "fzf"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/silee-tools/jg/releases/download/v0.1.6/jg-v0.1.6-darwin-amd64.tar.gz"
      sha256 "252a7bcc69802e7f937d43f9d8b9d75345930c2ffa9157aa25a228816674c551"

      define_method(:install) do
        bin.install "jg"
        zsh_completion.install "completions/_jg"
        bash_completion.install "completions/jg.bash" => "jg"
        (share/"jg"/"plugin").install "plugin/jg.plugin.zsh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/silee-tools/jg/releases/download/v0.1.6/jg-v0.1.6-darwin-arm64.tar.gz"
      sha256 "2d3bc36554e6f642c917da5bd01e70e3d4574f28d8b53502d930193e91245750"

      define_method(:install) do
        bin.install "jg"
        zsh_completion.install "completions/_jg"
        bash_completion.install "completions/jg.bash" => "jg"
        (share/"jg"/"plugin").install "plugin/jg.plugin.zsh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/silee-tools/jg/releases/download/v0.1.6/jg-v0.1.6-linux-amd64.tar.gz"
      sha256 "c8194cefc4c20cb690f527ce2def6e41f454c63bb7225f11b65c374f83f4fb7d"
      define_method(:install) do
        bin.install "jg"
        zsh_completion.install "completions/_jg"
        bash_completion.install "completions/jg.bash" => "jg"
        (share/"jg"/"plugin").install "plugin/jg.plugin.zsh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/silee-tools/jg/releases/download/v0.1.6/jg-v0.1.6-linux-arm64.tar.gz"
      sha256 "d376157446b2968d0c2c21a956b14b1c93c5df922668c08fd139ecd02c4296f9"
      define_method(:install) do
        bin.install "jg"
        zsh_completion.install "completions/_jg"
        bash_completion.install "completions/jg.bash" => "jg"
        (share/"jg"/"plugin").install "plugin/jg.plugin.zsh"
      end
    end
  end

  def caveats
    <<~EOS
      Run 'jg setup' to configure shell integration,
      then restart your shell or run: exec $SHELL
    EOS
  end

  test do
    assert_match "jg", shell_output("#{bin}/jg --help 2>&1")
  end
end
